// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRVNOlM3sX56wOd6oePUmo1KQfWHCR7lw',
    appId: '1:77975660188:web:2b6279099e01f806992f59',
    messagingSenderId: '77975660188',
    projectId: 'ilearn-app-6b0b7',
    authDomain: 'ilearn-app-6b0b7.firebaseapp.com',
    databaseURL: 'https://ilearn-app-6b0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ilearn-app-6b0b7.appspot.com',
    measurementId: 'G-TG5TQBQNDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE6tMLyJc73a3NRfTvOGE0hfUtWuaX_7A',
    appId: '1:77975660188:android:e7fe137c7a6943c4992f59',
    messagingSenderId: '77975660188',
    projectId: 'ilearn-app-6b0b7',
    databaseURL: 'https://ilearn-app-6b0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ilearn-app-6b0b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIf8K3nwPphBmriNfRxCjDCRY44nZin5M',
    appId: '1:77975660188:ios:d73da6207d55725f992f59',
    messagingSenderId: '77975660188',
    projectId: 'ilearn-app-6b0b7',
    databaseURL: 'https://ilearn-app-6b0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ilearn-app-6b0b7.appspot.com',
    iosClientId: '77975660188-jl4l8u0k8m08v7dr0mli3mo067dep5p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilearnProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIf8K3nwPphBmriNfRxCjDCRY44nZin5M',
    appId: '1:77975660188:ios:27afe05c0ef19051992f59',
    messagingSenderId: '77975660188',
    projectId: 'ilearn-app-6b0b7',
    databaseURL: 'https://ilearn-app-6b0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ilearn-app-6b0b7.appspot.com',
    iosClientId: '77975660188-v6pgstj1qfcj28ier97bgsae8hm475s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilearnProject.RunnerTests',
  );
}
